version: 0.0 #CodeDeployのバージョン現在は0.0のみ
os: linux #EC2内で使用するOS
files: 
    - source: /Wit/laravel/ #github内のどのファイルorフォルダをデプロイするか
      destination: ./var/www/laravel/ #ec2内のどの場所にデプロイするか
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall: #スクリプトを実行したいフェーズ
    - location: deploy.sh #スクリプトファイルの場所を相対パスで記述
      timeout: 300 #実行できなければ300msでタイムアウトする
