version: '3' 

services:
  php: 
    build: ./docker/php
    platform: 'linux/amd64'
    container_name: php
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
    depends_on:
      - mysql

  nginx:
    image: nginx
    platform: 'linux/amd64'
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    platform: 'linux/amd64'
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wit_db
      #MYSQL_ROOT_USER: root
      #MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: haruki
      MYSQL_PASSWORD: haruki
      TZ: 'Asia/Tokyo'
      
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    depends_on:
      - mysql-volume

  mysql-volume:
    image: busybox
    platform: 'linux/amd64'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: 'linux/amd64'
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      #- PMA_USER=root
      #- PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions